// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateTaskInput struct {
	Title    string    `json:"title"`
	Content  string    `json:"content"`
	Schedule time.Time `json:"schedule"`
	Done     bool      `json:"done"`
}

type UpdateTaskInput struct {
	Title    *string    `json:"title,omitempty"`
	Content  *string    `json:"content,omitempty"`
	Schedule *time.Time `json:"schedule,omitempty"`
	Done     *bool      `json:"done,omitempty"`
}
